# Generated by Django 3.2 on 2022-07-24 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_projects', '0003_auto_20220724_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='project_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
