# Generated by Django 3.2 on 2022-07-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_projects', '0004_clientproject_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='project_id',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
