# Generated by Django 3.2 on 2022-07-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'hidden'), (1, 'Public'), (2, 'coming soon')], default=0)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('hosted_url', models.URLField(blank=True)),
                ('screenshot', models.ImageField(blank=True, upload_to='media/portfolio-screenshots/')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('project_type', models.IntegerField(choices=[(0, 'website'), (1, 'app'), (2, 'game'), (3, 'other')], default=0)),
            ],
        ),
    ]
