# Generated by Django 3.2 on 2022-07-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
    ]
