# Generated by Django 3.2 on 2022-07-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_repo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(
                blank=True,
                upload_to='portfolio-screenshots/'),
        ),
    ]
